version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: question-maker
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: question-maker
    expose:
     - "8080"
    ports:
     - "8080:8080"
    command: -p 8080
