name: question-maker-job
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Installing modules
      run: npm i
    - name: prepare tests setup
      run: npm run setup-test
    - name: create migrations
      run: npm run migrate-test:postgres
    - name: Run tests 
      run: npm run test
    - name: drop db memory server instance
      run: npm run docker:down
